# Generated by Django 3.2.8 on 2021-11-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(help_text='Ingrese la marca del vehiculo', max_length=200)),
                ('cilindraje', models.FloatField(help_text='Ingrese el cilindraje')),
            ],
        ),
        migrations.CreateModel(
            name='Computadoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(help_text='Ingrese la marca de la computadora', max_length=200)),
                ('precio', models.IntegerField(help_text='Ingrese el precio de la computadora', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='libro',
            name='editorial',
            field=models.CharField(default=1, help_text='editorial del libro', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='numero_paginas',
            field=models.IntegerField(default=2, help_text='numero de paginas', max_length=1000),
            preserve_default=False,
        ),
    ]
