# Generated by Django 3.2.8 on 2021-11-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_auto_20211117_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='computadoras',
            name='codigo',
            field=models.IntegerField(default=2, help_text='Ingrese el codigo de la computadora', max_length=200),
            preserve_default=False,
        ),
    ]
